### PR TITLE
Support AWS Provider V5

### PR DESCRIPTION
**Pull request by max-lobur**
## what

Support AWS Provider V5
Linter fixes

## why

Maintenance

## references

https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.0.0

### CODE REVIEW

**Review by zdmytriv — APPROVED** [review]

**Comment by max-lobur** [comment]
Changed test according to https://github.com/cloudposse/terraform-aws-config-storage/blob/main/test/src/examples_complete_test.go#L41

**Pull request merged**
